import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header/Header";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";



export const URWNextArabic = localFont({
  src: [
    {
      path: "../public/fonts/URW-DIN-Arabic.ttf",
    },
  ],
  variable: "--font-URW-next-arabic",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      dir="rtl"
      className={cn("h-full", "antialiased", URWNextArabic.variable)}
    >
      <body  className={` ${URWNextArabic.variable} `}>
        <Header />
        {children}
        </body>
    </html>
  );
}
