import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/layout/Header/Header";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { NextIntlClientProvider } from 'next-intl';
import Footer from "@/components/layout/Footer/Footer";
import logo from "@/assets/logo.png"
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";


export const URWNextArabic = localFont({
  src: [
    {
      path: "../../public/fonts/URW-DIN-Arabic.ttf",
    },
  ],
  variable: "--font-URW-next-arabic",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: logo.src,
  },
};


export function generateStaticParams() {
  return routing.locales.map(locale => ({ lang: locale }));
}


export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang?: string }>;

}>) {
  const { lang = 'ar' } = await params;
  if (!routing.locales.includes(lang as any)) {
    notFound();
  }
  const messages = await getMessages();
  const direction = lang === 'ar' ? 'rtl' : 'ltr';
  return (
    <html
      lang={lang}
      dir={direction}
      className={cn("h-full", "antialiased", URWNextArabic.variable)}
    >
      <body className={` ${URWNextArabic.variable} `}>
        <NextIntlClientProvider messages={messages} locale={lang}>
          <Header />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
